version: '3.7'
services:
  dsl_es_node1:
    image: elasticsearch:7.13.4
    container_name: dsl_es_node1
    environment:
      - ES_JAVA_OPTS=-Xms256m -Xmx256m
    ports:
      - "9525:9525"
      - "9925:9925"
    volumes:
      - /Users/van/WorkSpace/ECE/EsCluster/DSL/es_node1/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - /Users/van/WorkSpace/ECE/EsCluster/DSL/es_node1/data:/usr/share/elasticsearch/data
    networks:
      - elastic
networks:
  elastic:
    driver: bridge