version: '3.7'
services:
  cfg_c1_es_node1:
    image: elasticsearch:7.13.4
    container_name: cfg_c1_es_node1
    environment:
      - ES_JAVA_OPTS=-Xms256m -Xmx256m
    ports:
      - "9526:9526"
      - "9926:9926"
    volumes:
      - /Users/van/WorkSpace/ECE/EsCluster/CFG_C1/es_node1/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - /Users/van/WorkSpace/ECE/EsCluster/CFG_C1/es_node1/data:/usr/share/elasticsearch/data
    networks:
      - elastic
  cfg_c1_es_node2:
    image: elasticsearch:7.13.4
    container_name: cfg_c1_es_node2
    environment:
      - ES_JAVA_OPTS=-Xms256m -Xmx256m
    ports:
      - "9527:9527"
      - "9927:9927"
    volumes:
      - /Users/van/WorkSpace/ECE/EsCluster/CFG_C1/es_node2/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - /Users/van/WorkSpace/ECE/EsCluster/CFG_C1/es_node2/data:/usr/share/elasticsearch/data
    networks:
      - elastic
networks:
  elastic:
    driver: bridge